version: '3'
services:
  snippet-box:
    image: therysin/snippet-box:1.0.0
    container_name: snippet-box
    volumes:
      - /path/to/host/data:/app/data
    ports:
      - 5000:5000
    restart: unless-stopped
